name: Publish
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: ${{github.repository_owner == 'asnowc'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish-Jsr
        run: npx jsr publish
